# STAGE 1: build Node static site
FROM node:22-slim AS site-builder

WORKDIR /app

# install deps and build
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# STAGE 2: build Go pseudonymizer (run `go mod tidy` before commit if Go dependencies change)
FROM golang:alpine AS go-builder

# build pseudonymizer
WORKDIR /app/pseudonymize
COPY server/pseudonymize/ .
RUN go mod download
RUN go build -o pseudonymize .

# build preprocessor
WORKDIR /app/preprocess
COPY server/preprocess/ .
RUN go mod download
RUN go build -o preprocess .

# STAGE 3: final image with NGINX + pseudonymizer
FROM nginx:alpine

RUN apk add --no-cache logrotate

# set working directory (nginx default)
WORKDIR /usr/share/nginx/html

# copy built static site from site-builder
COPY --from=site-builder /app/dist/ .
COPY robots.txt .
COPY /src/DMSans-Subset-Bold.woff2 ./src
COPY /src/DMSans-Subset-Bold.woff2 ./src

# copy the Go binary
# COPY --from=go-builder /app/pseudonymize /usr/local/bin/pseudonymize
COPY --from=go-builder /app/pseudonymize/pseudonymize /pseudonymize
COPY --from=go-builder /app/preprocess/preprocess /preprocess
RUN chmod +x /pseudonymize /preprocess

# custom NGINX config
COPY server/dev/nginx-dev.conf /etc/nginx/nginx.conf
COPY server/dev/default-dev.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /data/logs

# copy logrotate config & script
COPY server/logrotate.d/goaccess /etc/logrotate.d/goaccess
COPY server/run-logrotate.sh /usr/local/bin/run-logrotate.sh
RUN chmod +x /usr/local/bin/run-logrotate.sh

# copy entrypoint script to set up access log piping
COPY server/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# # default nginx foreground behavior being handled by entrypoint script
# CMD ["nginx", "-g", "daemon off;"]